swagger: '2.0'
info:
  description: |
    Official documentation for the rooibosd RESTful API.
  version: '1.0'
  title: rooibosd
  contact:
    name: rooibosd on GitHub
    url: https://github.com/squaresLab/rooibosd
host: rooibosd
basePath: /v1

definitions:
  Location:
    type: string
    description: >-
      Describes the location of a character in a body of text as a string of
      the form "line:col", where "line" is the one-indexed number of the line
      to which the character belongs, and "column" is the one-indexed number of
      the column to which the character belongs.
    example: "10:4"

  LocationRange:
    type: string
    example: "10:4::10:5"

  BoundTerm:
    type: object
    properties:
      term:
        type: string
        description: The name of the term.
        example: "cond"
      location:
        description: >-
          The location range of the source code to which this term is bound.
        $ref: '#/definitions/LocationRange'
      content:
        type: string
        description: >-
          The source code to which this term is bound.
        example: "x < 3"

  Environment:
    type: array
    items:
      $ref: '#/definitions/BoundTerm'

  Match:
    type: object
    properties:
      location:
        $ref: '#/definitions/LocationRange'
      environment:
        $ref: '#/definitions/Environment'

paths:
  /status:
    get:
      summary: Status of the server.
      description: >-
        Produces a diagnostic summary of the health of the server.
      produces:
        - application/json
      responses:
        204:
          description: Server is healthy and running.

  /matches:
    get:
      summary: Find all matches of a template in a source text.
      description: >-
        Finds all matches of a provided template in a given source text.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            description: >-
              A list of all matches that were found.
            items:
              $ref: '#/definitions/Match'
        400:
          description: Failed to parse provided template or source code.

  /substitute:
    get:
      summary: Substitutes a set of provided arguments into a given template.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: string
            description: >-
              The result of performing substitution on the input source.
            example: "x >= 3"
        400:
          description: Failed to parse provided arguments or source code.
